version: 2

sources:
  - name: raw
    schema: wk4_gwz_raw_data
    description: "raw data source of gwz"

    tables:
      - name: product
        identifier: raw_gz_product
        description: "products sold"
        columns:
          - name: products_id 
            description: primary key for this table
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE 
            description: purchase price

      - name: sales
        freshness: 
           warn_after: {count: 90, period: day}
        loaded_at_field: "CAST (date_date AS TIMESTAMP)"
      
        identifier: raw_gz_sales
        description: "one row per product id found in each order id"
        tests:
                - unique:
                   column_name: "(pdt_id || '-' ||orders_id)"  
                
        columns:
          - name: date_date
            description: date purchase made
          - name: orders_id
            description: foreign key to ship
          - name: products_id
            description: foreign key to ship
          - name: revenue
            description: "purchase price of product by quantity sold"
          - name: quantity
            description: "quantity purchased on the order"
            
      - name: ship
        identifier: raw_gz_ship
        description: "shipping information"
              
        columns:
          - name: orders_id
            description: primary key for this table
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: "price paid by customer for shipping" 
          - name: logCost
            description: "logistics costs for preparing the shipment" 
          - name: ship_cost
            description: "transporter costs paid by GWZ to ship order"   

      - name: sales_margin
        identifier: int_sales_margin
        description: "joined stg.sales and stg.products with aggregations for sales margins"
        tests:
          - unique:
              column_name: "(orders_id || '-' || products_id)"
          - not_null:
              column_name:
                - orders_id
                - products_id        
                - margin   
                - purchase_cost           
                - date_date             
                - revenue              
                - quantity
             
      - name: orders_margin
        identifier: int_orders_margin
        description: "calculating the orders margin based on the sales margin file"
        tests:
          - unique:
              column_name: "(orders_id || '-' || date_date)"
          - not_null:
              column_name:
                - orders_id
                - margin
                - purchase_cost      
                - date_date            
                - revenue           
                - quantity
           
      - name: operational_margin
        identifier: int_orders_operational
        description: "all information about the orders from an operational level including costs and margins"
        tests:
          - unique:
              column_name: "(orders_id || '-' || date_date)"
          - not_null:
              column_name:
                - orders_id             
                - margin   
                - purchase_cost               
                - date_date                         
                - quantity          
                - operational_margin       